### ISSUE TITLE
pbapclient.py doesn't work in my case

### ISSUE THREAD

**Issue by g0pher98** [nccgroup/nOBEX#11]
Hello! thank you for making this codes.

I tested 5 devices (android 3, iphone 2). however when i used `pbapclient.py`, i had problem.

When i tested with iphone, `*.vcf` file was created well. but every vcf files didn't contained contents  
However when i tested in android, i got this error.
```
Traceback (most recent call last):
  File "examples/pbapclient.py", line 134, in <module>
    sys.exit(main(sys.argv))
  File "examples/pbapclient.py", line 111, in main
    dump_dir(c, prefix+"telecom/pb", dest_dir+prefix+"telecom/pb")
  File "examples/pbapclient.py", line 60, in dump_dir
    hdrs, cards = c.get(src_path, header_list=[headers.Type(b'x-bt/vcard-listing')])
  File "/usr/local/lib/python3.6/dist-packages/nOBEX/client.py", line 296, in get
    raise OBEXError(response)
nOBEX.common.OBEXError: UnknownResponse(code=0xC6, data=b'\xcb\x00\x00\x00\x01'
```
To solve this error, I added print code for debug. the error is as below.
```
[DEBUG][request] Connect(data=(16, 0, 65535))
[DEBUG][request raw] b'\x80\x00\x1a\x10\x00\xff\xffF\x00\x13ya5\xf0\xf0\xc5\x11\xd8\tf\x08\x00 \x0c\x9af'
[DEBUG][request] Get(data=())
[DEBUG][request raw] b'\x83\x007\xcb\x00\x00\x00\x01\x01\x00\x19\x00t\x00e\x00l\x00e\x00c\x00o\x00m\x00/\x00p\x00b\x00\x00B\x00\x16x-bt/vcard-listing\x00'
[DEBUG][response] UnknownResponse(code=0xC6, data=b'\xcb\x00\x00\x00\x01'
```
i guess second response has problem. but i don't know detailed structure about "PBAP protocol" and code. plz tell me how to solve this problem. I want to run this code at iphone and android.

**Comment by sultanqasim** [comment]
I'll do some testing on iOS 14 or 15 when I get chance. I haven't been doing much with nOBEX over the past year. Which Android devices were you testing with?

**Comment by ysard** [comment]
Hi, I have the same problem here on Android 4.4.4:
```
Traceback (most recent call last):
      File "pbapclient.py", line 135, in <module>
        sys.exit(main(sys.argv))
      File "pbapclient.py", line 112, in main
        dump_dir(c, prefix+"telecom/pb", dest_dir+prefix+"telecom/pb")
      File "pbapclient.py", line 60, in dump_dir
        hdrs, cards = c.get(src_path, header_list=[headers.Type(b'x-bt/vcard-listing')])
      File "/home/pi/.virtualenvs/bluetooth/lib/python3.7/site-packages/nOBEX/client.py", line 290, in get
        raise OBEXError(response)
    nOBEX.common.OBEXError: UnknownResponse(code=0xD0, data=b''
```

But it works correctly on MIUI 11/Android 7.1.2

**Comment by ernestvh** [comment]
Hi, I've been having the same issue with Android 13 on a Samsung A52s 5G. I've used developer mode to select both PBAP v1.1 and v1.2 but that made no difference. I did find a solution tho!

The phone always returns 0xC6 as in the OP, which is OBEX error code 'Not Acceptable'. I don't know why. If I first try to list the virtual root directory (`c.listdir()`), the phone again responds with 'Not Acceptable', although I would expect it to say 'Forbidden' if I'm not allowed to list this directory. That's what an iPhone 8 with iOS 14.1 does, at least the one I've been testing with. On that device, the example client just works.

**Solution:**

If you first navigate to `telecom` by executing `c.setpath('telecom')`, it does work! So it seems that the phone wants you to be inside the telecom directory before executing the `PullvCardListing` method from the spec.

I was inspired to try this by Figure 4.2 from the PBAP spec (found here for PBAP v1.1.1: https://www.bluetooth.com/specifications/specs/phone-book-access-profile-1-1-1/). Altho it doesn't say that you HAVE to browse to `telecom` first, it seems to be part of the "phonebook browsing flow" which could explain these implementation differences.

Note that because we've changed path, the get function becomes something like this:

```
hdrs, cards = c.get('pb', header_list=[headers.Type(b'x-bt/vcard-listing')])
```

I could still use `telecom/pb` inside the get, but then it only worked on my Android and not the iOS device. Again there seems to be implementation differences to how they handle relative paths. The best way is thus to setpath to `telecom` and use a relative directory ('pb', 'ich', etc.), this way it works on both devices for me. I could also navigate to 'telecom/pb' by executing setpath twice, to move into telecom and pb respectively, and by then not passing any path (Name) to the get function. This also works with both devices.

I just wanted to test the listing function so I used below snippet:

```
c.setpath('telecom')
hdrs, cards = c.get('pb', header_list=[headers.Type(b'x-bt/vcard-listing')])
c.setpath(to_parent=True)
```

I'll have to properly integrate this change into the example `pbapclient.py` and create a pull request.

Here's a quick and dirty patch tho, which should work for any given src path or desired phonebook:

```
diff --git a/examples/pbapclient.py b/examples/pbapclient.py
index 48a848e..dc24e81 100755
--- a/examples/pbapclient.py
+++ b/examples/pbapclient.py
@@ -56,7 +56,12 @@ def dump_dir(c, src_path, dest_path):
         pass

     # Access the list of vcards in the directory
-    hdrs, cards = c.get(src_path, header_list=[headers.Type(b'x-bt/vcard-listing')])
+    src_path_l = src_path.split("/")
+    for path in src_path_l[0:-1]:
+        c.setpath(path)
+    hdrs, cards = c.get(src_path_l[-1], header_list=[headers.Type(b'x-bt/vcard-listing')])
+    for i in range(len(src_path_l)-1):
+        c.setpath(to_parent=True)

     if len(cards) == 0:
         print("WARNING: %s is empty, skipping", src_path)
```

As you can see it simply moves into the telecom folder containing the phonebook, and then moves back to the root before continuing with the rest of the example code.
