### ISSUE TITLE
UnknownResponse for vcard listing on Samsung

### ISSUE THREAD

**Issue by reematt** [nccgroup/nOBEX#3]
I am trying to run your solution on Ubuntu 16.04. When I run the pbapclient-download.py to download contacts from my phone (I tried Galaxy S7 and Galaxy S6) I am getting the following error: 

File "examples/pbapclient-download.py", line 84, in dump_dir
    hdrs, cards = c.get(src_path, header_list=[headers.Type(b'x-bt/vcard-listing')])
TypeError: 'UnknownResponse' object is not iterable

And this is the full traces of what I am getting:

Traceback (most recent call last):
  File "examples/pbapclient-download.py", line 150, in <module>
    sys.exit(main())
  File "examples/pbapclient-download.py", line 127, in main
    dump_dir(c, prefix+"telecom/pb", dest_dir+prefix+"telecom/pb")
  File "examples/pbapclient-download.py", line 84, in dump_dir
    hdrs, cards = c.get(src_path, header_list=[headers.Type(b'x-bt/vcard-listing')])
TypeError: 'UnknownResponse' object is not iterable

Can you please help?

**Comment by reematt** [comment]
I have tried now with iphone7 and it worked so I think your script DOES NOT support Android

**Comment by sultanqasim** [comment]
When I get time, I'll need to investigate the behaviour on Samsung devices
